services:
  node:
    image: "node:alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: >
      sh -c "yarn &&
             yarn build &&
             yarn start"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
networks:
  pokeapi_network:
    external: true
